export const route = {
  home: '/',
  dashboard: '/',
  campaigns: '/campaigns',
  campaignCreate: '/campaigns/create',
  campaignDetail: '/campaigns/$campaignId',
  campaignEdit: '/campaigns/$campaignId/edit',
  contacts: '/contacts',
  contactsImport: '/contacts/import',
  contactsValidate: '/contacts/validate',
  contactsCreateList: '/contacts/create-list',
  templates: '/templates',
  templatesCreate: '/templates/create',
  analytics: '/analytics',
  analyticsOverview: '/analytics/overview',
  settings: '/settings',
  agents: '/agents',
} as const