/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as TemplatesCreateRouteImport } from './routes/templates.create'
import { Route as ContactsContactListIdRouteImport } from './routes/contacts_/$contactListId'
import { Route as ContactsValidateRouteImport } from './routes/contacts/validate'
import { Route as ContactsImportRouteImport } from './routes/contacts/import'
import { Route as ContactsCreateListRouteImport } from './routes/contacts/create-list'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns_/$campaignId'
import { Route as CampaignsCreateRouteImport } from './routes/campaigns/create'
import { Route as AnalyticsOverviewRouteImport } from './routes/analytics.overview'
import { Route as TemplatesTemplateIdEditRouteImport } from './routes/templates_.$templateId.edit'
import { Route as ContactsContactListIdEditRouteImport } from './routes/contacts/$contactListId/edit'
import { Route as CampaignsCampaignIdEditRouteImport } from './routes/campaigns/$campaignId/edit'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampaignsRoute,
} as any)
const TemplatesCreateRoute = TemplatesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TemplatesRoute,
} as any)
const ContactsContactListIdRoute = ContactsContactListIdRouteImport.update({
  id: '/contacts_/$contactListId',
  path: '/contacts/$contactListId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsValidateRoute = ContactsValidateRouteImport.update({
  id: '/contacts/validate',
  path: '/contacts/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsImportRoute = ContactsImportRouteImport.update({
  id: '/contacts/import',
  path: '/contacts/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsCreateListRoute = ContactsCreateListRouteImport.update({
  id: '/contacts/create-list',
  path: '/contacts/create-list',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns_/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCreateRoute = CampaignsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => CampaignsRoute,
} as any)
const AnalyticsOverviewRoute = AnalyticsOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AnalyticsRoute,
} as any)
const TemplatesTemplateIdEditRoute = TemplatesTemplateIdEditRouteImport.update({
  id: '/templates_/$templateId/edit',
  path: '/templates/$templateId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactListIdEditRoute =
  ContactsContactListIdEditRouteImport.update({
    id: '/contacts/$contactListId/edit',
    path: '/contacts/$contactListId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignIdEditRoute = CampaignsCampaignIdEditRouteImport.update({
  id: '/$campaignId/edit',
  path: '/$campaignId/edit',
  getParentRoute: () => CampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/campaigns': typeof CampaignsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/analytics/overview': typeof AnalyticsOverviewRoute
  '/campaigns/create': typeof CampaignsCreateRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/contacts/create-list': typeof ContactsCreateListRoute
  '/contacts/import': typeof ContactsImportRoute
  '/contacts/validate': typeof ContactsValidateRoute
  '/contacts/$contactListId': typeof ContactsContactListIdRoute
  '/templates/create': typeof TemplatesCreateRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
  '/contacts/$contactListId/edit': typeof ContactsContactListIdEditRoute
  '/templates/$templateId/edit': typeof TemplatesTemplateIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/analytics/overview': typeof AnalyticsOverviewRoute
  '/campaigns/create': typeof CampaignsCreateRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/contacts/create-list': typeof ContactsCreateListRoute
  '/contacts/import': typeof ContactsImportRoute
  '/contacts/validate': typeof ContactsValidateRoute
  '/contacts/$contactListId': typeof ContactsContactListIdRoute
  '/templates/create': typeof TemplatesCreateRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
  '/contacts/$contactListId/edit': typeof ContactsContactListIdEditRoute
  '/templates/$templateId/edit': typeof TemplatesTemplateIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/campaigns': typeof CampaignsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/analytics/overview': typeof AnalyticsOverviewRoute
  '/campaigns/create': typeof CampaignsCreateRoute
  '/campaigns_/$campaignId': typeof CampaignsCampaignIdRoute
  '/contacts/create-list': typeof ContactsCreateListRoute
  '/contacts/import': typeof ContactsImportRoute
  '/contacts/validate': typeof ContactsValidateRoute
  '/contacts_/$contactListId': typeof ContactsContactListIdRoute
  '/templates/create': typeof TemplatesCreateRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
  '/contacts/$contactListId/edit': typeof ContactsContactListIdEditRoute
  '/templates_/$templateId/edit': typeof TemplatesTemplateIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/campaigns'
    | '/settings'
    | '/templates'
    | '/analytics/overview'
    | '/campaigns/create'
    | '/campaigns/$campaignId'
    | '/contacts/create-list'
    | '/contacts/import'
    | '/contacts/validate'
    | '/contacts/$contactListId'
    | '/templates/create'
    | '/campaigns/'
    | '/contacts'
    | '/campaigns/$campaignId/edit'
    | '/contacts/$contactListId/edit'
    | '/templates/$templateId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/settings'
    | '/templates'
    | '/analytics/overview'
    | '/campaigns/create'
    | '/campaigns/$campaignId'
    | '/contacts/create-list'
    | '/contacts/import'
    | '/contacts/validate'
    | '/contacts/$contactListId'
    | '/templates/create'
    | '/campaigns'
    | '/contacts'
    | '/campaigns/$campaignId/edit'
    | '/contacts/$contactListId/edit'
    | '/templates/$templateId/edit'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/campaigns'
    | '/settings'
    | '/templates'
    | '/analytics/overview'
    | '/campaigns/create'
    | '/campaigns_/$campaignId'
    | '/contacts/create-list'
    | '/contacts/import'
    | '/contacts/validate'
    | '/contacts_/$contactListId'
    | '/templates/create'
    | '/campaigns/'
    | '/contacts/'
    | '/campaigns/$campaignId/edit'
    | '/contacts/$contactListId/edit'
    | '/templates_/$templateId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  CampaignsRoute: typeof CampaignsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  ContactsCreateListRoute: typeof ContactsCreateListRoute
  ContactsImportRoute: typeof ContactsImportRoute
  ContactsValidateRoute: typeof ContactsValidateRoute
  ContactsContactListIdRoute: typeof ContactsContactListIdRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  ContactsContactListIdEditRoute: typeof ContactsContactListIdEditRoute
  TemplatesTemplateIdEditRoute: typeof TemplatesTemplateIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/templates/create': {
      id: '/templates/create'
      path: '/create'
      fullPath: '/templates/create'
      preLoaderRoute: typeof TemplatesCreateRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/contacts_/$contactListId': {
      id: '/contacts_/$contactListId'
      path: '/contacts/$contactListId'
      fullPath: '/contacts/$contactListId'
      preLoaderRoute: typeof ContactsContactListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/validate': {
      id: '/contacts/validate'
      path: '/contacts/validate'
      fullPath: '/contacts/validate'
      preLoaderRoute: typeof ContactsValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/import': {
      id: '/contacts/import'
      path: '/contacts/import'
      fullPath: '/contacts/import'
      preLoaderRoute: typeof ContactsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/create-list': {
      id: '/contacts/create-list'
      path: '/contacts/create-list'
      fullPath: '/contacts/create-list'
      preLoaderRoute: typeof ContactsCreateListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns_/$campaignId': {
      id: '/campaigns_/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/create': {
      id: '/campaigns/create'
      path: '/create'
      fullPath: '/campaigns/create'
      preLoaderRoute: typeof CampaignsCreateRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/analytics/overview': {
      id: '/analytics/overview'
      path: '/overview'
      fullPath: '/analytics/overview'
      preLoaderRoute: typeof AnalyticsOverviewRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/templates_/$templateId/edit': {
      id: '/templates_/$templateId/edit'
      path: '/templates/$templateId/edit'
      fullPath: '/templates/$templateId/edit'
      preLoaderRoute: typeof TemplatesTemplateIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactListId/edit': {
      id: '/contacts/$contactListId/edit'
      path: '/contacts/$contactListId/edit'
      fullPath: '/contacts/$contactListId/edit'
      preLoaderRoute: typeof ContactsContactListIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/edit': {
      id: '/campaigns/$campaignId/edit'
      path: '/$campaignId/edit'
      fullPath: '/campaigns/$campaignId/edit'
      preLoaderRoute: typeof CampaignsCampaignIdEditRouteImport
      parentRoute: typeof CampaignsRoute
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsOverviewRoute: typeof AnalyticsOverviewRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsOverviewRoute: AnalyticsOverviewRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface CampaignsRouteChildren {
  CampaignsCreateRoute: typeof CampaignsCreateRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CampaignsCampaignIdEditRoute: typeof CampaignsCampaignIdEditRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsCreateRoute: CampaignsCreateRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CampaignsCampaignIdEditRoute: CampaignsCampaignIdEditRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesCreateRoute: typeof TemplatesCreateRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesCreateRoute: TemplatesCreateRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  CampaignsRoute: CampaignsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  ContactsCreateListRoute: ContactsCreateListRoute,
  ContactsImportRoute: ContactsImportRoute,
  ContactsValidateRoute: ContactsValidateRoute,
  ContactsContactListIdRoute: ContactsContactListIdRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  ContactsContactListIdEditRoute: ContactsContactListIdEditRoute,
  TemplatesTemplateIdEditRoute: TemplatesTemplateIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
